Shopping page
konevm/exceed__testshop pull request #4
Opened 2022-06-08 06:21 UTC by konevm

Create cart and shopping page, create wrapper as HOC for modals

2022-06-08 08:38 UTC, bobkov-evgeny requested changes

2022-06-08 08:38 UTC, bobkov-evgeny commented on src/components/Routes/routesEnum.ts
> +export enum Routes {
Let's create new folder at /src and name it "constants", inside this folder let's create new file app-routes.constants.ts. Inside put your enum, just rename it to "AppRoutes". 

And please keep in mind enum naming convention example: 
var WinnerEnum = {
    PLAYER_1: 1,
    PLAYER_2: 2,
    DRAW: 0
};

CamelCase for enum name, and UPPERCASE for enum fields

2022-06-08 08:38 UTC, bobkov-evgeny commented on src/App.tsx
> +import { Routes as routes } from "./components/Routes/routesEnum";
Don't really understand why we need this "as" operator )

2022-06-08 08:38 UTC, bobkov-evgeny commented on src/Pages/Cart/Cart.tsx
> +import "./Cart.scss";
Please check your imports

2022-06-08 08:38 UTC, bobkov-evgeny commented on src/Pages/Cart/Cart.tsx
> +      {cart.length === 0 && <Link to={productsLink}> Continue shopping </Link>}
Can't we just pass here Routes.products variable?

2022-06-08 08:38 UTC, bobkov-evgeny commented on src/Pages/MainPage/MainPage.tsx
> +        <Link to="new" className="banner__ad">
Forgot to use routes enum?

2022-06-08 08:38 UTC, bobkov-evgeny commented on src/Pages/Shop/Shop.tsx
> +const List: React.FC<IShopList> = ({ products, new: isNew }) => {
I think we simply can rename this prop to isNew (in interface as well)

2022-06-08 08:38 UTC, bobkov-evgeny commented on src/components/CartItem/CartItem.tsx
> +  const { name, image, price, amount } = product;
To my mind, it's better to rename "image" to "imageUrl"

2022-06-08 08:38 UTC, bobkov-evgeny commented on src/components/CartItem/CartItem.tsx
> +      <div className="item__image" style={{ backgroundImage: `url(${image})` }}></div>
We have empty div, let's close it />

2022-06-08 08:38 UTC, bobkov-evgeny commented on src/components/EcoProducts/EcoProducts.tsx
> +        <Link className="info__link" to="products">
AppRoutes enum?

2022-06-08 08:38 UTC, bobkov-evgeny commented on src/components/Glowing/Glowing.tsx
> +        <Link className="glowing__link" to="products">
The same -  AppRoutes enum?

2022-06-08 08:38 UTC, bobkov-evgeny commented on src/components/Header/Header.tsx
> +      <Link to={Routes.main} className="header__logo" style={{ backgroundImage: `url(${Logo})` }} />
If "Logo" is also URL string, let's rename it to logoUrl

2022-06-08 09:20 UTC, konevm commented on src/App.tsx
> +import { Routes as routes } from "./components/Routes/routesEnum";
Routes already exists in react-router-dom

2022-06-08 09:31 UTC, konevm commented on src/components/Routes/routesEnum.ts
> +export enum Routes {
done

2022-06-08 09:33 UTC, konevm commented on src/Pages/Cart/Cart.tsx
> +      {cart.length === 0 && <Link to={productsLink}> Continue shopping </Link>}
i don't want to write `../${AppRoutes.PRODUCTS}` twice

2022-06-08 09:35 UTC, konevm commented on src/Pages/MainPage/MainPage.tsx
> +        <Link to="new" className="banner__ad">
"new" is rewrite soon

2022-06-08 09:41 UTC, konevm commented on src/components/EcoProducts/EcoProducts.tsx
> +        <Link className="info__link" to="products">
done

2022-06-08 09:42 UTC, konevm commented on src/components/Glowing/Glowing.tsx
> +        <Link className="glowing__link" to="products">
done

2022-06-08 09:43 UTC, konevm commented on src/components/Header/Header.tsx
> +      <Link to={Routes.main} className="header__logo" style={{ backgroundImage: `url(${Logo})` }} />
done

2022-06-08 09:44 UTC, konevm commented on src/components/CartItem/CartItem.tsx
> +      <div className="item__image" style={{ backgroundImage: `url(${image})` }}></div>
done

2022-06-08 09:44 UTC, konevm commented on src/components/CartItem/CartItem.tsx
> +  const { name, image, price, amount } = product;
done

2022-06-08 09:47 UTC, konevm commented on src/Pages/Shop/Shop.tsx
> +const List: React.FC<IShopList> = ({ products, new: isNew }) => {
done

2022-06-09 08:20 UTC, bobkov-evgeny approved these changes

2022-06-09 08:20 UTC, merged